
edit()
startEdit()

cd('/Servers/myserver/Log/myserver')
cmo.setStacktraceDepth(5)
cmo.setRotationType('bySize')
cmo.setDomainLogBroadcasterBufferSize(1)
cmo.setLog4jLoggingEnabled(false)
cmo.setNumberOfFilesLimited(true)
cmo.setDateFormatPattern('yyyy-M-d ahh\' ±\'mm\'∑÷\'ss\'√Î\' z')
cmo.setBufferSizeKB(8)
cmo.setFileMinSize(500)
cmo.setLoggerSeverity('Info')
cmo.setRotateLogOnStartup(true)
cmo.setServerLoggingBridgeUseParentLoggersEnabled(false)
cmo.setDomainLogBroadcastSeverity('Notice')
cmo.setRedirectStderrToServerLogEnabled(false)
cmo.setStdoutLogStack(true)
cmo.setLogFileSeverity('Debug')
cmo.setFileCount(7)
cmo.setMemoryBufferSize(10)
cmo.setStdoutFormat('standard')
cmo.setRedirectStdoutToServerLogEnabled(false)
cmo.setFileName('logs/myserver.log')
cmo.setStdoutSeverity('Debug')
cmo.setMemoryBufferSeverity('Debug')

activate()
exit()

